name: Smoke Tests - PR

on:
  pull_request:
    branches: [ main ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Chrome
          - uses: browser-actions/setup-chrome@v1
          - run: chrome --version

      - name: Instalar Chrome Driver
         - uses: nanasess/setup-chromedriver@v2.2.0

      - name: Run Test
        run: mvn test -Dtest=RunCucumberTest -Dbrowser=chrome-ci